gsub_file("config/routes.rb", /get \"home\/index\"/, '')
gsub_file("config/routes.rb", /get \"users\/index\"/, '')
gsub_file("config/routes.rb", /get \"users\/new\"/, '')
gsub_file("config/routes.rb", /get \"users\/create\"/, '')
gsub_file("config/routes.rb", /get \"users\/edit\"/, '')
gsub_file("config/routes.rb", /get \"users\/update\"/, '')
gsub_file("config/routes.rb", /get \"users\/destroy\"/, '')
gsub_file("config/routes.rb", /get \"dashboard\/index\"/, '')
